### ISSUE TITLE
What happened to the wait_events iterator in the 0.17 API?

### ISSUE THREAD

**Issue by fschutt** [glium/glium#1616]
In the pre-0.17 API, there was a very handy wait_events iterator for the event loop. It blocks the flow until a new event is encountered, which is good for non-game applications. I can't find information on what this was replaced by.

Basically, I am searching for a replacement for this code, which worked fine:

```rust
for ev in self.display.borrow().wait_events() {
    // delegate event to other function
}
```

`poll_events` is way less efficient, because it consumes 100% CPU. If blocked with a timeout, it still acts on **every** event **in sequence**, making it impossible to get the CPU usage down, plus it makes the whole application slow. How do I get the `wait_events` behaviour back with the new API? I don't want events not related to my window.

Also, why are the `glium::glutin::DeviceEvent` and `glium::glutin::Event::DeviceEvent` named exactly the same, it's confusing as hell.

How do I filter the input **only if my window is in focus**? Why was this removed? I can't even get the `x` and `y` of my mouse anymore, because the `AxisId.0` field is private.

It went from this:

```
match *event {
    WindowEvent::MouseMoved (x, y)  => { should_redraw = handle_mouse_move(&renderer, x, y); },
}
``` 

to this:

```
    use glium::glutin::Event::WindowEvent as WEv;
    use glium::glutin::Event::DeviceEvent as DEv;
    use glium::glutin::WindowEvent as W_Ev;
    use glium::glutin::DeviceEvent as D_Ev;

    match *event {
        DEv { ref event, .. } => match *event {
            D_Ev::Motion { axis, value, .. }      => {
                let x = { if axis.0 == 0 { value } else { 0.0 }}; // doesn't even work because axis.0 is private
                let y = { if axis.0 == 1 { value } else { 0.0 }};
                should_redraw = handle_mouse_move(&renderer, x, y);
            },
    }
```

It also triggers on events that aren't even related to my window, like keypresses outside the current window. `poll_events` and `run_forever` eat 100% CPU and make simple things such as window resizing  slow as hell. What the hell happened?

**Comment by martinhath** [comment]
It seems the `Axis` issue is solved by [this](https://github.com/tomaka/winit/commit/3d9e8da9ec543d3277a62650ecd90c456317e74a#diff-b0c6567016cc00656693792c8e1582d2) commit in `winit`. I'm not sure exactly when the change went through here, but in Glium `0.17.1`, `axis` is only a `u32`.

**Comment by fschutt** [comment]
@martinhath it still isn't fixed. I still get events from outside my window. It's not even possible to get which pixel the mouse is currently hovering over. This is ridiculous. Every window API ever can tell me which pixel the mouse is over, except for glium / winit. And it still uses 100% CPU.

I will do a pull request to see if I can fix this.

**Comment by fschutt** [comment]
I'll close this because this is a winit issue that has been referenced numerous times.

See:

- https://github.com/tomaka/winit/issues/276
- https://github.com/tomaka/winit/issues/231

The decision was due to MacOS' resize handling. I can't say that using 100% CPU usage just so that a window resizes properly on MacOS was a good decision. So I can only say that I am not happy with the decisions. I decided to backport an important crash fix [here](https://github.com/fschutt/glium-backport/tree/glium_backport). This branch uses the pre-0.17 API, because I need something that works.
