### ISSUE TITLE
Cannot find macro `uniform` in this scope

### ISSUE THREAD

**Issue by Kirottu** [glium/glium#1888]
So, my project is failing to compile with this error message, regarding my editor the errors origin is `glium-0.28.0/src/macros.rs`

And here is the full compilation error:
```
error: cannot find macro `uniform` in this scope
  --> src/main.rs:72:24
   |
72 |           let uniforms = glium::uniform! {
   |  ________________________^
73 | |             matrix: [
74 | |                 [1.0, 0.0, 0.0, 0.0],
75 | |                 [0.0, 1.0, 0.0, 0.0],
...  |
79 | |             tex: &texture,
80 | |         };
   | |_________^
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to previous error
```

It worked just fine before too, it just spontaneously stopped working.

**Comment by est31** [comment]
Can you try removing code until you get a minimum reproducible example? Alternatively, check whether older versions still compile, maybe you changed something seemingly unrelated and it caused the breakage.

**Comment by Kirottu** [comment]
It seemingly stopped working after i implemented code to load a texture. Which is pretty bizarre, as after that i disabled the texture loading code with nothing changed.

**Comment by InnocentusLime** [comment]
This error persists even on glium 0.29.0. Here's the minimal example

```rust
fn main() {
  glium::uniform! {
    foo : 2,
    bar : 2.0f32,
  };
}
```

This produces the same error.

My guess is that `uniform!` macro doesn't use its absolute path in one of the branches (see [line 72 in `uniform!` definition](https://github.com/glium/glium/blob/master/src/macros.rs#L72))

The fix would be to write 

```rust
$crate::macros::uniform!($($field: $value),*)
```

instead
